/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UsersController;
import Model.Users;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author XDORRO
 */
public class SettingJPanel extends javax.swing.JPanel {
    private JFrame This;
    private int user_id;
    private final UsersController controller;
    
    /**
     *
     * @param This
     * @param user
     */
    public SettingJPanel(JFrame This, Users user) {
        this.This = This;
        this.controller = new UsersController(This);
        initComponents();
        setFocusable(true);

        if (user != null) {
            this.user_id = user.getUser_id();
            String username = user.getUsername();
            boolean gender = user.isGender();
            
            labelUsername.setText(
                (username.length() <= 24 ? username : username.substring(0, 21) + "...").toUpperCase()
            );
            labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/Images/icon_" + (gender==true ? "boy" : "girl") + ".png"
            )));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        panelUsername = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        panelChangePassword = new javax.swing.JPanel();
        labelChangePassword = new javax.swing.JLabel();
        labelNewpass = new javax.swing.JLabel();
        txtNewpass = new javax.swing.JPasswordField();
        labelRepass = new javax.swing.JLabel();
        txtRenewPass = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 245));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_logout.png"))); // NOI18N
        btnLogout.setText("ĐĂNG XUẤT");
        btnLogout.setToolTipText("ĐĂNG XUẤT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        panelUsername.setBackground(new java.awt.Color(255, 255, 255));
        panelUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelUsername.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(29, 161, 242));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_boy.png"))); // NOI18N
        labelUsername.setText("ADMIN");

        javax.swing.GroupLayout panelUsernameLayout = new javax.swing.GroupLayout(panelUsername);
        panelUsername.setLayout(panelUsernameLayout);
        panelUsernameLayout.setHorizontalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsernameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        panelUsernameLayout.setVerticalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelChangePassword.setBackground(new java.awt.Color(255, 255, 255));
        panelChangePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelChangePassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChangePassword.setText("ĐỔI MẬT KHẨU");

        labelNewpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelNewpass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNewpass.setText("Mật khẩu mới: ");

        txtNewpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNewpass.setForeground(new java.awt.Color(153, 153, 153));
        txtNewpass.setText("Nhập mật khẩu");
        txtNewpass.setToolTipText("Nhập mật khẩu mới");
        txtNewpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewpassFocusLost(evt);
            }
        });

        labelRepass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelRepass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRepass.setText("Nhập lại mật khẩu mới: ");

        txtRenewPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtRenewPass.setForeground(new java.awt.Color(153, 153, 153));
        txtRenewPass.setText("Nhập mật khẩu");
        txtRenewPass.setToolTipText("Nhập lại mật khẩu mới");
        txtRenewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRenewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRenewPassFocusLost(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("LƯU THAY ĐỔI");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("HỦY");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChangePasswordLayout = new javax.swing.GroupLayout(panelChangePassword);
        panelChangePassword.setLayout(panelChangePasswordLayout);
        panelChangePasswordLayout.setHorizontalGroup(
            panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChangePasswordLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangePasswordLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(labelChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelChangePasswordLayout.createSequentialGroup()
                        .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelRepass, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(labelNewpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewpass)
                            .addComponent(txtRenewPass))))
                .addContainerGap())
        );
        panelChangePasswordLayout.setVerticalGroup(
            panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePasswordLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNewpass)
                    .addComponent(labelNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRenewPass)
                    .addComponent(labelRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("–––––   THÔNG TIN CÁ NHÂN –––––   ");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(panelChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginJFrame().setVisible(true);
        This.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtNewpass.setText("Nhập mật khẩu");
        txtNewpass.setForeground(new Color(153, 153, 153));
        txtRenewPass.setText("Nhập mật khẩu");
        txtRenewPass.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        controller.changePassword(user_id, txtNewpass, txtRenewPass);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNewpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewpassFocusGained
        if (txtNewpass.getText().trim().equals("Nhập mật khẩu")) {
            txtNewpass.setText("");
            txtNewpass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtNewpassFocusGained

    private void txtNewpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewpassFocusLost
        if (txtNewpass.getText().trim().equals("")) {
            txtNewpass.setText("Nhập mật khẩu");
            txtNewpass.setForeground(new Color(153, 153, 153));
        } else {
            txtNewpass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtNewpassFocusLost

    private void txtRenewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRenewPassFocusGained
        if (txtRenewPass.getText().trim().equals("Nhập mật khẩu")) {
            txtRenewPass.setText("");
            txtRenewPass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtRenewPassFocusGained

    private void txtRenewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRenewPassFocusLost
        if (txtRenewPass.getText().trim().equals("")) {
            txtRenewPass.setText("Nhập mật khẩu");
            txtRenewPass.setForeground(new Color(153, 153, 153));
        } else {
            txtRenewPass.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtRenewPassFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelChangePassword;
    private javax.swing.JLabel labelNewpass;
    private javax.swing.JLabel labelRepass;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelChangePassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPasswordField txtNewpass;
    private javax.swing.JPasswordField txtRenewPass;
    // End of variables declaration//GEN-END:variables
}
